In [1]:
import numpy as np
import gym
from gym import spaces
from gym.utils import seeding
import gym_grid_world
import random
import numpy as np
import sys
sys.path.append('/Users/AmberS/miniconda3/lib/python3.5/site-packages')

def main():
    
    np.random.seed(0)
    alpha = 0.9 # learning rate
    epsilon = 0 # epsilon greedy policy
    gamma = 0.9 # discount factor
    env = gym.make('grid_world-v0')
    T = 26
    M = env.action_space.n
    print(M)
    N = env.state_space.n
    k = 0
    d = {}
    for i in range(N):
        for j in range(N):
            d.update([((i,j),k)])
            k+=1
    # 'N' denotes number of states
    # 'M' denotes number of actions
    # 'T' denotes the terminal state
    Q = np.zeros((N*N,M)) # initializing the Q matrix 
    tot_epi = 200 # denotes the maximum number of episodes 
    choice = [1,2] # for implementing epsilon-greedy policy
    dist = [epsilon, 1-epsilon]
    
    for ep in range(tot_epi):
        #s = np.random.randint(1,N*N) # randomly select initial state for each episode
        env.reset()
        s1,s2 = env.state
        #print(s1-1,s2-1)
        #print(d)
        #s = d[(s1-1,s2-1)]
        s = d[(s1,s2)]
        itr = 0
        ep_choice = random.choices(choice, dist)
        if ep_choice == 2:
            a = np.argmax(Q[s,:]) # this is not epsilon greedy
        else:
            a = np.random.randint(0,M)
        while itr < 30000:
            obs, reward, done, info = env.step(a)
            s1,s2 = obs
            #s_pr = d[(s1-1,s2-1)]
            s_pr = d[(s1,s2)]
            ep_choice = random.choices(choice, dist)
            if ep_choice == 2:
                a_pr = np.argmax(Q[s_pr,:]) # this is not epsilon greedy
            else:
                a_pr = np.random.randint(0,M)
            #print(ep_choice)
            #print(a)
            
            #print(reward)
            
            a_pr = np.argmax(Q[s,:])
            Q[s,a] = Q[s,a] + alpha*(reward + gamma*Q[s_pr,a_pr] - Q[s,a])
            s = s_pr
            a = a_pr
            itr +=1
        epsilon = epsilon*0.9
        
    v_star = np.zeros((N,N))
    pi_star = np.zeros((N,N))
    for i in range(N):
        for j in range(N):
            s = d[(i,j)]
            f = np.amax(Q[s,:])
            f1 = np.argmax(Q[s,:])
            v_star[4-i,j] = f
            pi_star[4-i,j] = f1
    '''
    v_star = np.amax(Q,axis=1)
    
    v_star_i = v_star[::-1]
    v_star = np.reshape(v_star_i,(5,5))
    pi_star = np.argmax(Q,axis=1)
    pi_star_i = pi_star[::-1]
    pi_star = np.reshape(pi_star_i,(5,5))
    '''
    print('----Optimal Value function----')
    print(v_star)
    #print(v_star_i)
    print('-----pi_star-----')
    print(pi_star)
    
    #print(Q)
    

main() # invoking the main function

4
----Optimal Value function----
[[21.97748529 24.4194281  21.97748529 18.4501845  16.60505978]
 [16.90176309 21.97748529 16.93027899 17.09563411 14.79990688]
 [17.14480769 19.77973676 17.34967131 11.98452209 13.27358837]
 [15.46117573 17.80176308 12.06506043 13.27617919 11.34411363]
 [10.5132031  16.02158677 12.95299324 11.47990883  8.88475738]]
-----pi_star-----
[[2. 0. 3. 2. 3.]
 [0. 0. 0. 3. 0.]
 [2. 0. 3. 1. 0.]
 [2. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]]


Guide to pi_star:
Value:0----->Action Up
Value:1----->Action Down
Value:2----->Action Right
Value:3----->Action Left