In [1]:
import numpy as np
import gym
from gym import spaces
from gym.utils import seeding
import gym_grid_world
import random
from random import choices
import numpy as np


def main():
    np.random.seed(0)
    alpha = 0.5 # learning rate
    epsilon = 0 # epsilon greedy policy
    #epsilon = 0
    gamma = 0.9 # discount factor
    env = gym.make('grid_world-v0')
    T = 26
    M = env.action_space.n
    #print(M)
    N = env.state_space.n
    # 'N' denotes number of states
    # 'M' denotes number of actions
    # 'T' denotes the terminal state
    k = 0
    d = {}
    for i in range(N):
        for j in range(N):
            d.update([((i,j),k)])
            k+=1
    
    Q = np.zeros((N*N,M)) # initializing the Q matrix 
    tot_epi = 100 # denotes the maximum number of episodes 
    choice = [1,2] # for implementing epsilon-greedy policy
    dist = [epsilon, 1-epsilon]
    
    for ep in range(tot_epi):
        #s = np.random.randint(0,N-1) # randomly select initial state for each episode
        env.reset()
        s1,s2 = env.state
        #print(s1-1,s2-1)
        #print(d)
        #s = d[(s1-1,s2-1)]
        s = d[(s1,s2)]
        
        itr = 0
        while itr < 10000:
            ep_choice = random.choices(choice, dist)
            if ep_choice == 2:
                a = np.argmax(Q[s,:]) # this is not epsilon greedy
            else:
                a = np.random.randint(0,M) # M-1+1
                
            obs, reward, done, info = env.step(a)
            s1,s2 = obs
            #s_pr = d[(s1-1,s2-1)]
            s_pr = d[(s1,s2)]
            a_pr = np.argmax(Q[s_pr,:])
            Q[s,a] = Q[s,a] + alpha*(reward + gamma*Q[s_pr,a_pr] - Q[s,a])
            s = s_pr
            itr +=1
    #print(Q)
    
    v_star = np.zeros((N,N))
    pi_star = np.zeros((N,N))
    for i in range(N):
        for j in range(N):
            s = d[(i,j)]
            f = np.amax(Q[s,:])
            f1 = np.argmax(Q[s,:])
            v_star[4-i,j] = f
            pi_star[4-i,j] = f1
    '''
    v_star = np.amax(Q,axis=1)
    
    v_star_i = v_star[::-1]
    v_star = np.reshape(v_star_i,(5,5))
    pi_star = np.argmax(Q,axis=1)
    pi_star_i = pi_star[::-1]
    pi_star = np.reshape(pi_star_i,(5,5))
    '''
    print('----Optimal Value function----')
    print(v_star)
    #print(v_star_i)
    print('-----pi_star-----')
    print(pi_star)

main() # invoking the main function

----Optimal Value function----
[[21.97748529 24.4194281  21.97748529 19.4194281  17.47748529]
 [19.77973676 21.97748529 19.77973676 17.80176308 16.02158677]
 [17.80176308 19.77973676 17.80176308 16.02158677 14.4194281 ]
 [16.02158677 17.80176308 16.02158677 14.4194281  12.97748529]
 [14.4194281  16.02158677 14.4194281  12.97748529 11.67973676]]
-----pi_star-----
[[2. 0. 3. 0. 3.]
 [0. 0. 0. 3. 3.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Guide to pi_star:
Value:0----->Action Up
Value:1----->Action Down
Value:2----->Action Right
Value:3----->Action Left