In [2]:
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 10 20:04:28 2018

@author: baranwa2
"""
import numpy as np
import importlib, random
import matplotlib.pyplot as plt
import gym_env
import gym

import sarsa
sarsa = importlib.reload(sarsa)
import Risca
Risca = importlib.reload(Risca)
import single_chain_class_version
single_chain_class_version = importlib.reload(single_chain_class_version)
import Reinforce
Reinforce = importlib.reload(Reinforce)

#Creating object of Sarsa class and passing environment
env = gym.make('single_chain-v0')
sarsa_agent = sarsa.SarsaAgent(env)

#-----------------SARSA Parametrs-----------
epsilon = 1
alpha = 0.1
gamma = 0.9
episode_max_length = 1000
num_episodes = 10
#count_var = int(num_episodes/500)
#new_var = count_var+1
tot_reward_sarsa = np.zeros((5,num_episodes))
episode_50 = [i for i in range(num_episodes)]
#np.random.seed(0)

#------------REPS Parameters--------------------
#features = [[1, 0, 0], [1, 1, 1], [1, 2, 4], [1, 3, 9], [1, 4, 16]]
features = [[1, 0, 0], [1, 1, 1], [1, 2, 4], [1, 3, 9]]

features = np.array(features)

theta0 = np.dot(10,np.random.random_sample(features[0].shape[0]))
eta0 = 10
x0 = np.append(theta0, eta0)
epsilon_r = 1

#R = np.array([[0, 0], [0, 2], [0, 2], [0, 2], [10, 2]])
R = np.array([[0, 0], [0, 2], [0, 2], [10, 2]])
info_loss=0.5
n_policy_updates=10
n_samples=500
opt_method='L-BFGS-B'
tot_reward_reps = np.zeros((5,n_policy_updates))
episode_reps = [i for i in range(n_policy_updates)]

#----Policy Gradient Parameters----------
reinforce_agent = Reinforce.ReinforceAgent(env)
risca_agent = Risca.ReinforceCis(env)
alphan = 0.01
ep_max = 25
epsilonn = 0
t_steps = 40
episodes = 10
tot_reward_reinforce = np.zeros((5,episodes))
#episode_reps = [i for i in range(n_policy_updates)]
tot_reward_risca = np.zeros((5,episodes))

for item in range(5):
    rewards_sarsa = []
    rewards_reinforce = []
    rewards_risca = []
    rewards_reps = []
    policy = single_chain_class_version.Policy_REPS(env)
    agent = single_chain_class_version.run_REPS()
    rewards_sarsa = sarsa_agent.train(epsilon, alpha, gamma, episode_max_length, num_episodes)
    rewards_reps, V, policy, q_sa, theta, eta = agent.REPS(env, R, policy, features, x0, epsilon_r, info_loss,
                                      n_policy_updates, n_samples, opt_method)
    rewards_sarsa/= episode_max_length
    rewards_risca = risca_agent.train(alphan,ep_max,epsilonn,t_steps,episodes)
    rewards_reinforce = reinforce_agent.train(alphan,ep_max,epsilonn,t_steps,episodes)
    tot_reward_sarsa[item,:] = rewards_sarsa
    tot_reward_reps[item,:] = rewards_reps
    tot_reward_reinforce[item,:] = rewards_reinforce
    tot_reward_risca[item,:] = rewards_risca
    

mean1 = np.mean(tot_reward_sarsa, axis=0)
mean2 = np.mean(tot_reward_reps, axis=0)
mean3 = np.mean(tot_reward_reinforce, axis=0)
mean4 = np.mean(tot_reward_risca, axis=0)
#mean1[0] = np.amin(tot_reward[:,0])
green_point = dict(markerfacecolor='g', marker='D')
print('---SARSA_Means----')
print(mean1)
print(len(episode_50))
print('---REPS_Means---')
print(mean2)
print(len(episode_50))
print('---REINFORCE_Means---')
print(mean3)
print(len(episode_50))
print('---REINFORCE+IS+Causality_Means---')
print(mean4)
print(len(episode_50))

#Set_up for the plots
plt.figure(1)
plt.boxplot(tot_reward_sarsa,positions = episode_50 , showmeans = True)
line1, = plt.plot(episode_50,mean1,'b')
plt.boxplot(tot_reward_reps,positions = episode_50 , showmeans = True)
line2, = plt.plot(episode_50,mean2,'r')
plt.boxplot(tot_reward_reinforce,positions = episode_50 , showmeans = True)
line3, = plt.plot(episode_50,mean3,'c')
plt.boxplot(tot_reward_risca,positions = episode_50 , showmeans = True)
line4, = plt.plot(episode_50,mean4,'k')
plt.title('Performance of various algorithms on Two State environment')
plt.xlabel('Policy Updates')
plt.ylabel('Average Reward')
label_line = ['SARSA','REPS','REINFORCE','REINFORCE_IS_CA']
plt.legend([line1,line2,line3,line4], label_line)
plt.show()



#################################################

Policy update 1/10 - 
dual value optim :  5.120682462076758
dual gradient theta :  0.42004525193113
dual gradient eta :  2.0187161420966033
KL Divergence:  1.207848688550032
J: 9.63; b'ABNORMAL_TERMINATION_IN_LNSRCH'
eta is: 1.967741579769796
Policy : 
 [[0.622 0.378]
 [0.662 0.338]
 [0.928 0.072]
 [1.    0.   ]]

#################################################

Policy update 2/10 - 
dual value optim :  10.743900122921636
dual gradient theta :  0.0005049554602386985
dual gradient eta :  0.12567164568223
KL Divergence:  0.15083525837627254
J: 9.74; b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
eta is: 1.5768584444798672
Policy : 
 [[0.753 0.247]
 [0.819 0.181]
 [0.993 0.007]
 [1.    0.   ]]

#################################################

Policy update 3/10 - 
dual value optim :  10.78533106483157
dual gradient theta :  0.0001898684309802374
dual gradient eta :  0.12598271162834962
KL Divergence:  0.004958894975667895
J: 9.75

Policy update 3/10 - 
dual value optim :  10.782645332874406
dual gradient theta :  0.0002077574155911684
dual gradient eta :  0.1477791768331551
KL Divergence:  0.004083264749910286
J: 9.69; b'ABNORMAL_TERMINATION_IN_LNSRCH'
eta is: 1.5714547197018438
Policy : 
 [[0.627 0.373]
 [0.68  0.32 ]
 [1.    0.   ]
 [1.    0.   ]]

#################################################

Policy update 4/10 - 
dual value optim :  10.773211853346773
dual gradient theta :  0.0002694981764069721
dual gradient eta :  0.14770471777645966
KL Divergence:  0.1967558529935202
J: 9.78; b'ABNORMAL_TERMINATION_IN_LNSRCH'
eta is: 1.5714547197018438
Policy : 
 [[0.766 0.234]
 [0.91  0.09 ]
 [1.    0.   ]
 [1.    0.   ]]

#################################################

Policy update 5/10 - 
dual value optim :  10.776371256233674
dual gradient theta :  0.000268956895797602
dual gradient eta :  0.14770208933464168
KL Divergence:  0.07248610959522706
J: 9.80; b'ABNORMAL_TERMINATION_IN_LNSRCH'
eta is: 1.571454719701

Policy update 5/10 - 
dual value optim :  10.78523473331831
dual gradient theta :  0.0005375475260948906
dual gradient eta :  0.1274629374383771
KL Divergence:  5.380416576679888e-07
J: 9.80; b'ABNORMAL_TERMINATION_IN_LNSRCH'
eta is: 1.5764491759955628
Policy : 
 [[0.914 0.086]
 [0.996 0.004]
 [1.    0.   ]
 [1.    0.   ]]

#################################################

Policy update 6/10 - 
dual value optim :  10.78523473331831
dual gradient theta :  0.0005375475260948906
dual gradient eta :  0.1274629374383771
KL Divergence:  1.7982440272488097e-08
J: 9.79; b'ABNORMAL_TERMINATION_IN_LNSRCH'
eta is: 1.5764491759955628
Policy : 
 [[0.914 0.086]
 [0.996 0.004]
 [1.    0.   ]
 [1.    0.   ]]

#################################################

Policy update 7/10 - 
dual value optim :  10.78523473331831
dual gradient theta :  0.0005375475260948906
dual gradient eta :  0.1274629374383771
KL Divergence:  6.010099615295769e-10
J: 9.79; b'ABNORMAL_TERMINATION_IN_LNSRCH'
eta is: 1.576449175

<Figure size 640x480 with 1 Axes>